In [6]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt

In [7]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [8]:
#turn it into matrix m number of rows and n is the number of columns
print(f"x Shape:{X_train.shape},X Type{type(X_train)}")
print(X_train)


x Shape:(3, 4),X Type<class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
